name: API mock server

on:
  push:
    branches:
      - master

jobs:
  deploy-mock:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Login to Heroku Container registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: make deploy-mock

## Uncomment the following job step in order to publish API documentation with basic auth
#  deploy-api:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Checkout repository
#      uses: actions/checkout@v2
#    - name: Login to Heroku Container registry
#      env:
#        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
#      run: make deploy-api
